server:
  port: 9002

feign:
  hystrix: 
   enabled: true

eureka: # 绑定服务端的地址
 client: 
  # 注意这个是消费方， 不提供任何服务， 所以不进行注册  register-with-eureka: false
  service-url: 
   defaultZone: http://eureka-server-7001:7001/eureka/,http://eureka-server-7002:7002/eureka/,http://eureka-server-7003:7003/eureka/