package cn.cnm.webservice.impl;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import cn.cnm.webservice.HelloWS;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.3.3
 * 2019-10-26T16:06:16.121+08:00
 * Generated source version: 3.3.3
 *
 */
@WebServiceClient(name = "HelloWSImplService",
                  wsdlLocation = "http://127.0.0.1:8098/webservice-server/hellowsimpl?wsdl",
                  targetNamespace = "http://impl.webservice.cnm.cn/")
public class HelloWSImplService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://impl.webservice.cnm.cn/", "HelloWSImplService");
    public final static QName HelloWSImplPort = new QName("http://impl.webservice.cnm.cn/", "HelloWSImplPort");
    static {
        URL url = null;
        try {
            url = new URL("http://127.0.0.1:8098/webservice-server/hellowsimpl?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(HelloWSImplService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "http://127.0.0.1:8098/webservice-server/hellowsimpl?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public HelloWSImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public HelloWSImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public HelloWSImplService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public HelloWSImplService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public HelloWSImplService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public HelloWSImplService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns HelloWS
     */
    @WebEndpoint(name = "HelloWSImplPort")
    public HelloWS getHelloWSImplPort() {
        return super.getPort(HelloWSImplPort, HelloWS.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns HelloWS
     */
    @WebEndpoint(name = "HelloWSImplPort")
    public HelloWS getHelloWSImplPort(WebServiceFeature... features) {
        return super.getPort(HelloWSImplPort, HelloWS.class, features);
    }

}
